### ISSUE TITLE
插件无法自动化

### ISSUE THREAD

**Issue by Chasejsun** [KKKyrie/marie#2]
已经填写好marriage.js的value字段，editor并没有修改
需要手动点击marie按钮填充：
「双方基本信息」
「预约日期」和「预约登记城市」

无法填充：
「双方个人信息」

chrome版本 114.0.5735.133
麻烦作者看看什么原因

**Comment by Deadpoolmine** [comment]
> 已经填写好marriage.js的value字段，editor并没有修改 需要手动点击marie按钮填充： 「双方基本信息」 「预约日期」和「预约登记城市」
> 
> 无法填充： 「双方个人信息」
> 
> chrome版本 114.0.5735.133 麻烦作者看看什么原因

问题在于onMessage的action返回的都是FILL_PAGE_2

**Comment by Deadpoolmine** [comment]
``> 已经填写好marriage.js的value字段，editor并没有修改 需要手动点击marie按钮填充： 「双方基本信息」 「预约日期」和「预约登记城市」
> 
> 无法填充： 「双方个人信息」
> 
> chrome版本 114.0.5735.133 麻烦作者看看什么原因

将marriage.js的163行左右的FILL_PAGE_3分支改为下面即可：
```javascript
        else if (action === 'FILL_PAGE_3') {
        // 自动选择预约民政局和日期
        try {
          that.autoFillTimeAndBase();
          sendResponse('自动选择日期和结婚所在市');
        } catch (error) {
          console.log(error)
          // 填充人员信息
          that.autoFillCoupleInfoForm();
          sendResponse('自动填写新人信息！！！！！');
        }
}
```

**Comment by KKKyrie** [comment]
> 已经填写好marriage.js的value字段，editor并没有修改 需要手动点击marie按钮填充： 「双方基本信息」 「预约日期」和「预约登记城市」
> 
> 无法填充： 「双方个人信息」
> 
> chrome版本 114.0.5735.133 麻烦作者看看什么原因

fixed.
请 pull 下最新的 main 分支上的代码

**Comment by KKKyrie** [comment]
> ``> 已经填写好marriage.js的value字段，editor并没有修改 需要手动点击marie按钮填充： 「双方基本信息」 「预约日期」和「预约登记城市」
> 
> > 无法填充： 「双方个人信息」
> > chrome版本 114.0.5735.133 麻烦作者看看什么原因
> 
> 将marriage.js的163行左右的FILL_PAGE_3分支改为下面即可：
> 
> ```js
>         else if (action === 'FILL_PAGE_3') {
>         // 自动选择预约民政局和日期
>         try {
>           that.autoFillTimeAndBase();
>           sendResponse('自动选择日期和结婚所在市');
>         } catch (error) {
>           console.log(error)
>           // 填充人员信息
>           that.autoFillCoupleInfoForm();
>           sendResponse('自动填写新人信息！！！！！');
>         }
> }
> ```

不建议这么 hack......

**Comment by KKKyrie** [comment]
> 已经填写好marriage.js的value字段，editor并没有修改 需要手动点击marie按钮填充： 「双方基本信息」 「预约日期」和「预约登记城市」
> 
> 无法填充： 「双方个人信息」
> 
> chrome版本 114.0.5735.133 麻烦作者看看什么原因

已修复。  
pull 下 main 分支的最新代码
